# -*- coding: utf-8 -*-
"""Generating Pythonic Code

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sC0zbem1ieoVEihCFjkFUMUJLwtgimKQ
"""

import sys

sys.path

import os
STLIBLOC = '/usr/local/lib/python3.6/dist-packages'
os.listdir(STLIBLOC)
max_files = 100
count = 0
with open("input.txt","a",encoding="utf-8") as f:
  print("Inside with..")
  for path, directories, files in os.walk(STLIBLOC):
    print("Path",path)
    print("Directories",directories)
    print("Files",files)
    count+=1
    print("Incrementing count..")
    if count>max_files:
      print("Breaking..")
      break
    for i in files:
      if ".py" in i:
        print("Found files.")
        try:
          print("In try")
          with open(os.path.join(path, i),"r") as data_f:
            contents = data_f.read()
            print(contents)
          f.write(contents)
          f.write('\n')
        except Exception as e:
          print(str(e))

!ls

!git clone https://github.com/sourcecode369/unconventional-neural-networks

input.

os.listdir('unconventional-neural-networks/char-rnn-tensorflow/')

!mkdir unconventional-neural-networks/char-rnn-tensorflow/data/code/
!mv input.txt unconventional-neural-networks/char-rnn-tensorflow/data/code/

!python unconventional-neural-networks/char-rnn-tensorflow/train.py --data_dir=unconventional-neural-networks/char-rnn-tensorflow/data/code/ --num_epochs=5000

!python unconventional-neural-networks/char-rnn-tensorflow/sample.py -n=5000 >> unconventional-neural-networks/char-rnn-tensorflow/out.txt

